[custom]
;解决DNS泄露，无分流群组
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL

; 以下是代理群组部分
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇰🇷 韩国节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇹🇷 土耳其节点`[]🇮🇳 印度节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇻🇳 越南节点`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50

; 各国家/地区代理群组
custom_proxy_group=🇭🇰 香港节点`select`.*Hong Kong.*
custom_proxy_group=🇹🇼 台湾节点`select`.*Taiwan.*
custom_proxy_group=🇸🇬 新加坡节点`select`.*Singapore.*
custom_proxy_group=🇯🇵 日本节点`select`.*Japan.*
custom_proxy_group=🇺🇸 美国节点`select`.*United States.*
custom_proxy_group=🇰🇷 韩国节点`select`.*South Korea.*
custom_proxy_group=🇨🇦 加拿大节点`select`.*Canada.*
custom_proxy_group=🇬🇧 英国节点`select`.*Great Britain.*
custom_proxy_group=🇹🇷 土耳其节点`select`.*Turkey.*
custom_proxy_group=🇮🇳 印度节点`select`.*India.*
custom_proxy_group=🇳🇱 荷兰节点`select`.*Netherlands.*
custom_proxy_group=🇫🇷 法国节点`select`.*France.*
custom_proxy_group=🇩🇪 德国节点`select`.*Germany.*
custom_proxy_group=🇻🇳 越南节点`select`.*Vietnam.*

enable_rule_generator=true
overwrite_original_rules=true
